FROM node:18-alpine3.14 as build
WORKDIR /usr/src/bot
COPY package*.json ./

RUN npm install
RUN npm i -g tsc-watch

COPY ./src ./
COPY ./tsconfig.json ./
COPY ./docker ./docker

ENTRYPOINT /usr/src/bot/docker/entrypoint-dev.sh
