version: "3"
services:
  bot:
    container_name: "fiibot-dev"
    build:
      context: "../"
      dockerfile: "./docker/Dockerfile.dev"
    volumes:
      - "..:/usr/src/bot"
    env_file:
      - "../.env"
